WITH raw_listings AS (SELECT * FROM AIRBNB.RAW.RAW_LISTINGS)
SELECT
    ID,
    LISTING_URL,
    NAME,
    ROOM_TYPE,
    MINIMUM_NIGHTS,
    HOST_ID,
    PRICE,
    CREATED_AT,
    UPDATED_AT
    FROM
        raw_listings